/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as My_recipesRouteImport } from './routes/my_recipes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmisRouteImport } from './routes/amis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'
import { Route as CollectionsSplatRouteImport } from './routes/collections/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const My_recipesRoute = My_recipesRouteImport.update({
  id: '/my_recipes',
  path: '/my_recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmisRoute = AmisRouteImport.update({
  id: '/amis',
  path: '/amis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSplatRoute = CollectionsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CollectionsRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amis': typeof AmisRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/login': typeof LoginRoute
  '/my_recipes': typeof My_recipesRoute
  '/search': typeof SearchRoute
  '/collections/$': typeof CollectionsSplatRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amis': typeof AmisRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/login': typeof LoginRoute
  '/my_recipes': typeof My_recipesRoute
  '/search': typeof SearchRoute
  '/collections/$': typeof CollectionsSplatRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amis': typeof AmisRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/login': typeof LoginRoute
  '/my_recipes': typeof My_recipesRoute
  '/search': typeof SearchRoute
  '/collections/$': typeof CollectionsSplatRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amis'
    | '/auth'
    | '/collections'
    | '/login'
    | '/my_recipes'
    | '/search'
    | '/collections/$'
    | '/recipes/$id'
    | '/users/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amis'
    | '/auth'
    | '/collections'
    | '/login'
    | '/my_recipes'
    | '/search'
    | '/collections/$'
    | '/recipes/$id'
    | '/users/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/amis'
    | '/auth'
    | '/collections'
    | '/login'
    | '/my_recipes'
    | '/search'
    | '/collections/$'
    | '/recipes/$id'
    | '/users/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmisRoute: typeof AmisRoute
  AuthRoute: typeof AuthRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  LoginRoute: typeof LoginRoute
  My_recipesRoute: typeof My_recipesRoute
  SearchRoute: typeof SearchRoute
  RecipesIdRoute: typeof RecipesIdRoute
  UsersIdRoute: typeof UsersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my_recipes': {
      id: '/my_recipes'
      path: '/my_recipes'
      fullPath: '/my_recipes'
      preLoaderRoute: typeof My_recipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amis': {
      id: '/amis'
      path: '/amis'
      fullPath: '/amis'
      preLoaderRoute: typeof AmisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$': {
      id: '/collections/$'
      path: '/$'
      fullPath: '/collections/$'
      preLoaderRoute: typeof CollectionsSplatRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsSplatRoute: typeof CollectionsSplatRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSplatRoute: CollectionsSplatRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmisRoute: AmisRoute,
  AuthRoute: AuthRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  LoginRoute: LoginRoute,
  My_recipesRoute: My_recipesRoute,
  SearchRoute: SearchRoute,
  RecipesIdRoute: RecipesIdRoute,
  UsersIdRoute: UsersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
